### ISSUE TITLE
Unable to install SABnzbd plugin on TrueNAS-12.0-U8.1

### ISSUE THREAD

**Issue by luckyluke699** [RogerAirgood/iocage-plugin-sabnzbd#3]
I am unable to install SABnzbd plugin within TrueNAS 12U8, as it is failing on install (as per error below). I am unable to connect via the shell for long enough to ascertain what is happening from the SABnzbd logs unfortunately.

System: TrueNAS-12.0-U8.1 Core
Plugin: SABnzbd v3.5.3
Errors:

/usr/local/etc/rc.d/sabnzbd: WARNING: failed to start sabnzbd
Error: sabnzbd had a failure Exception: RuntimeError Message: Last 10 lines: /usr/local/etc/rc.d/sabnzbd: WARNING: failed to start sabnzbd sabnzbd not running? (cat). sed: /usr/local/sabnzbd/sabnzbd.ini: No such file or directory /usr/local/etc/rc.d/sabnzbd: WARNING: failed to start sabnzbd Partial plugin destroyed
I can confirm other users on TrueNAS-12.0-U8.1 Core experience the same issue, after opening a thread there: https://www.truenas.com/community/threads/12-0-u8-1-core-sabnzbd-partial-plugin.101313/#post-697649

Thank you in advance if you can help,
Luke

**Comment by ConorBeh** [comment]
Likely something changed with the package upstream. I'll have a look this week.

**Comment by luckyluke699** [comment]
Thank you for replying so quickly. Look forward to hearing from
you. Kind regards, Luke

**Comment by ConorBeh** [comment]
```
root@sabtest:~ # service sabnzbd start
Starting sabnzbd.
Not all required Python modules are available, please check requirements.txt
Missing module: importlib_resources
You can read more at: https://sabnzbd.org/wiki/installation/install-off-modules
If you still experience problems, remove all .pyc files in this folder and subfolders
/usr/local/etc/rc.d/sabnzbd: WARNING: failed to start sabnzbd
```
Looks like the package is actually missing a dependency: `py38-importlib-resources`
It's not listed here: https://www.freshports.org/news/sabnzbdplus

While it would be easy to install that package either in post_install.sh or in the artifact, I'm hesitant to do that as it's tech debt and this needs to be fixed upstream. I've reached out to the port's maintainer.

**Comment by ConorBeh** [comment]
Fixed upstream: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=264093

**Comment by luckyluke699** [comment]
Thank you very much indeed to yourself and those upstream who've worked on resolving this issue. Much appreciated! Luke
